### ISSUE TITLE
Access to Media Keys in WebWorks

### ISSUE THREAD

**Issue by timwindsor** [blackberry/WebWorks-Community-APIs#167]
Moving from the Framework to Community blackberry/BB10-WebWorks-Framework#577

This is a feature request to get WebWorks access to the device's media keys. It is already available in Cascades as described here: https://developer.blackberry.com/cascades/reference/bb__multimedia__mediakeywatcher.html

Media Keys might be handy for a number of tasks. In my case I'd like to use them in order to control the volume of remote systems.

Depends on #166

**Comment by timwindsor** [comment]
The approach will need to follow the example of [QtBridge](https://github.com/blackberry/WebWorks-Community-APIs/tree/master/BB10-Cordova/QtBridge) and [SystemDialog](https://github.com/blackberry/WebWorks-Community-APIs/tree/master/BB10-Cordova/SystemDialog)

**Comment by tfung** [comment]
I will start looking into this issue.

**Comment by timwindsor** [comment]
@tfung This one is very similar to #383 which @trsong is working on. He spent some time learning how the QtBridge plugins work, so you may want to work together to learn how they are done.
