### ISSUE TITLE
Porting PhoneGap BarcodeScanner API

### ISSUE THREAD

**Issue by alextoughg** [blackberry/WebWorks-Community-APIs#197]
Hello, 

Here is my analysis of the BarcodeScanner API. Feel free to comment/criticize constructively/question: 

API FOR BARCODESCANNER PLUGIN: 

data BarcodeScanner.BarcodeType = QR_CODE |
				DATA_MATRIX | 
				UPC_E | 
				UPC_A | 
				EAN_8 | 
				EAN_13 |
				CODE_128 |
				CODE_39 |
				CODE_93 |
				CODABAR | 
				ITF | 
				RSS14 | 
				PDF417 | 
				RSS_EXPANDED | 
				AZTEC 

/**
 * Scans the barcode, calling the function error if a device error occurred, or calling the function 
 * success otherwise.
 * @param success
 *	The function to be called if no device error occurred. It takes in one argument:
 *	an object with a data field (the decoded text of the barcode image), a type 
 *	field (type of barcode detected, of type BarcodeType) and a cancelled field 
 *     (whether or nor the user cancelled the scan). 
 */

window.plugins.barcodeScanner.scan(success, fail)

Example: 

window.plugins.barcodeScanner.scan(
    function(result) {
        if (result.cancelled === true) {
            alert("The scan was cancelled");
        } else {
            alert("Decoded barcode text: " + result.text);
        }
    }, function(error) {
        alert("Failed to scan barcode: " + error);
    }
);

data BarcodeScanner.EncodeFormat = CONTACT | 
							    LOCATION | 
							    EMAIL | 
							    PHONE | 
							    SMS | 
							    TEXT
							   	
/**
 * Encodes text into a Barcode image
 * @param format 
 *	The BarcodeScanner.EncodeFormat of the specified data
 * @param data 
 * 	The data to encode. Must be a string for EMAIL, PHONE, SMS and TEXT types.
 *       Must be a BarcodeContact for CONTACT type and BarcodeLocation for LOCATION type.
 *       BarcodeLocation is an object with two fields: longitude and latitude. 
 *       BarcodeContact is an object with eight fields: address, birthday, email, name, nickname, 
 *       note, telephone and url. 
 * @param success 
 * 	Callback function on successful barcode encode.
 *	File URI or base64 string (with the contents of the QR code as a bitmap) is passed 
 *      as argument to the success function.
 * @param fail 
 *	Callback function on error. Error message is passed in as a argument. 
 * @param options 
 *	An object containing optional encoding options. This object contains three fields:
 *		- width: Desired width of the image (default is 200)
 *		- height: Desired height of the image (default is also 200)
 *		- destinationType: Determines the format of the returned value. Default: 
 *		BarcodeScanner.DestinationType.DATA_URL: Base64 string containing the bitmap image. 
 */

window.plugins.barcodeScanner.encode(format, data, success, fail, options)

Example:

// Encodes a url into a 300x300 image
window.plugins.barcodeScanner.encode(
    BarcodeScanner.EncodeFormat.TEXT,
    "http://www.ibm.com",
    function(success) {
        alert("encode success: " + success);
    },
    function(fail) {
        alert("encoding failed: " + fail);
    },
    {width: 300, height: 300}
);

sources: https://github.com/phonegap/phonegap-plugins/tree/master/Android/BarcodeScanner
https://github.com/phonegap/phonegap-plugins/tree/master/BlackBerry/BarcodeScanner

Thanks,

Alex

**Comment by timwindsor** [comment]
Duplicated by #386
