### ISSUE TITLE
Mongoose Plugin issue with unquoted listening port

### ISSUE THREAD

**Issue by timwindsor** [blackberry/WebWorks-Community-APIs#279]
If the listening port is specified without quotes, the Mongoose plugin will crash on this line: https://github.com/blackberry/WebWorks-Community-APIs/blob/master/BB10-Cordova/Mongoose/plugin/src/blackberry10/native/src/Mongoose_ndk.cpp#L91

It would be nice to harden this and make it more robust.

**Comment by umcsdon** [comment]
Fixed.
