### ISSUE TITLE
EmailSender plugin should support HTML emails

### ISSUE THREAD

**Issue by timwindsor** [blackberry/WebWorks-Community-APIs#292]
MessageBuilder can take an HTML type, so if we can add a flag to the API for type, we should be able to accept both Plain text and HTML emails in this API.

**Comment by t3slaughter** [comment]
Did anything come of this? We need to send html in the body of an email using invokeEmailComposer?
Thanks,
Todd

**Comment by timwindsor** [comment]
This should be supported by the plugin - you can get it from this repo, or from the plugin registry using the cli: http://plugins.cordova.io/#/package/com.blackberry.community.emailsenderplugin
