### ISSUE TITLE
Can't get googleanalyticsplugin to work properly

### ISSUE THREAD

**Issue by analytik** [blackberry/WebWorks-Community-APIs#375]
Hi,

I'm not sure if I missed something. Installed community.googleanalyticsplugin to my Cordova/WebWorks 2.2 project, I did add my correct GA tracking ID, and I can run trackPageview and trackEvent functions.

However, in Web Inspector, I can only see connections to 
http://localhost:8472/com.blackberry.community.googleanalyticsplugin/trackAll

when I have queueing turned on, the urldecoded response is always
{"code":9,"msg":"event tracking error: Network busy","keepCallback":false} 

when I have queueing turned off, I get a normal-looking result:
 {"code":1,"data":"Finished event tracking","keepCallback":false} 

Nothing shows in GA realtime reports, though. Not on device, not in simulator, not with a debug build, not with a production build (testing with a Q10 device with 10.2.1, and with a simulator with 10.3.1).
Any ideas how to investigate this further? Since the call itself is made in Native, I cannot see the actual communication with Google Analytics servers.

Any suggestions will be appreciated.

**Comment by analytik** [comment]
Tim,

The application has been tracking for a few days, however, it seems that some bugs were introduced when merging - in this project, index.js has these lines when loading UUID:

```
if ("" == m_uuid) {
    m_uuid = storage.loadData('uuid');
}
```

However, the merged one in https://github.com/blackberry/GAPlugin/blob/master/src/blackberry10/index.js#L312

has this
```
if ("" == m_uuid) {
    m_uuid = storage.loadData('uuid');
    m_uuid = storage.saveData("");
}
```

which resets UUID every time app initializes gaPlugin; and I don't see any API to override it from the WebWorks app and set the UUID property.

**Comment by analytik** [comment]
Oh, and now I found out that it tracks only one custom dimension per pageload? Good heavens, this plugin could use a complete rewrite someday.

**Comment by timwindsor** [comment]
I'm going to close this one, but I've opened two specific issues to look into the problems you've found. I should have someone looking at them shortly.

**Comment by analytik** [comment]
Thanks, Tim!

Sorry for not submitting a normal pull request like a proper githubian, but I'm not even sure my changes are a proper solution. Here's the diff, hopefully some of it will help with investigation at least.

```diff
@@ -241,7 +243,7 @@
         bAccountSet = false,
         bRandomUuid = false,
         bSendBusy = false,
-        bUseQueue = false;
+        bUseQueue = false,
         bCustomDimension = false;
 
     var DEFAULT_DELAY = 500,
@@ -255,9 +257,7 @@
     //***********************************
     var account = function(value) {
         if (undefined != value) {
-            // UA-xxxxxxxx-x
-            // 0123456789012 <-index
-            if ((value.length != 13) || (value.substr(0,3) != "UA-") || (value.charAt(11) != '-')) {
+            if (value.length < 8 || value.substr(0,3) != "UA-") {
                 return "Invalid GA account, should be in the format UA-xxxxxxxx-x";
             }
             m_account = value;
@@ -309,22 +307,29 @@
             // If no storage uuid, create one with random
             if ("" == m_uuid) {
                 m_uuid = storage.loadData('uuid');
-                m_uuid = storage.saveData("");
             }
             if ("" == m_uuid){
                 m_uuid = randomizeUuid();
+                console.log("No UUID in storagem generating random one: " + m_uuid);
+            }
+            else {
+                console.log("Loaded UUID from storage: " + m_uuid);
             }
             // store UUID
-            return storage.saveData("uuid", m_uuid);
+            var ret = storage.saveData("uuid", m_uuid);
+            if (ret) {
+                console.log("Error saving uuid in local storage")
+                return ret;
+            }
+            return m_uuid;
         }
        return m_uuid;
     };
 
     var customdimension = function(index, value) {
-
-        if ( (undefined != value) && (undefined != index) ){
+        if (typeof index !== "undefined" && typeof value !== "undefined") {
             // Set custom dimension for next function call
-            m_customDimension = "&cd";
+            m_customDimension += "&cd";
             // index is the index of the custom dimension in user's GA account
             m_customDimension += index;
             m_customDimension += "=";
```
