### ISSUE TITLE
Barcode/QR Scanner will not display on screen after first run. 

### ISSUE THREAD

**Issue by arcaderob** [blackberry/WebWorks-Community-APIs#391]
After working with @timwindsor on ticket https://github.com/blackberry/WebWorks-Community-APIs/issues/389 created by @mattgrande , we have come to find that the barcode/qr scanner does not work after the first run. (This can also be replicated in the sample)

I scanned the QR code and the scanner closed and displayed the app with the data returned from the scanner. Upon tapping the scan button again, the scanner appears blank on the device's screen, BUT it will still "scan" the code. In other words, the scanner continues to read and return data, but it only displays the scanner on the screen the first time it is run.

Tested on Balckberry Z30 10.2.1.3062

**Comment by timwindsor** [comment]
Yes I'm seeing this too. Works fine on 10.3.1, but reproduces with 10.2.1.2102 after either a first scan or after a cancelled scan. I'm looking into it.

**Comment by arcaderob** [comment]
Thanks @timwindsor Hope that it's not too much work for you!

**Comment by arcaderob** [comment]
Is there any news on this issue?

**Comment by timwindsor** [comment]
I'm not sure what is going on. There's no error message that I can see, so I've asked for help from some other experts here. Hopefully there's a workaround or error in my code they can spot quickly.

**Comment by arcaderob** [comment]
Any updates?

**Comment by timwindsor** [comment]
Still working on it. I've got a better idea of what's going on, and some thoughts on how to fix it. I expect it will take me a few days though.

**Comment by arcaderob** [comment]
Thanks for the update! Happy coding!

**Comment by timwindsor** [comment]
Took me a bunch of trial and error, but eventually I had a brainwave. Give this a try (also published to the registry) and see if it's working for you.

**Comment by arcaderob** [comment]
I have tried it out and everything seems to be working well. Thank you for all your help!

**Comment by timwindsor** [comment]
Awesome. I think there's some things we might continue to work on, but at this point I think all the truly critical issues are taken care of.

**Comment by arcaderob** [comment]
Agreed. I will add that the folder structure of the BarcodeScanner is different than the rest of the plugins. There is an extra "tier". I don't know if you want to change this to keep it uniform with the rest of the plugins, but, again, great work!

**Comment by timwindsor** [comment]
Do you mean compared to other plugins in the same repo, or other plugin projects elsewhere?

**Comment by arcaderob** [comment]
My apologies. I was looking at the wrong folder. Everything is in order.
