### ISSUE TITLE
[BB10-Cordova/BarcodeScanner] Dotted Data Matrix Code doesn´t work

### ISSUE THREAD

**Issue by Anollya** [blackberry/WebWorks-Community-APIs#395]
Hello,

i´ve a problem with the BB10-Cordova/BarcodeScanner.
Dotted Data Matix Code doesn´t work.

Here is an DMC example:
http://2.bp.blogspot.com/_5lL1y9ELMFM/RuqSvwzuNrI/AAAAAAAAAkw/cBNhZnGfFbY/s400/media_guru_Cool_Datamatrix.png

How can i fix it? 

Thank you

**Comment by timwindsor** [comment]
Do you know what is encoded in that image? I couldn't get it decoded with a third party decoder either.

However, I tried a couple test images with Data Matrix, included some Dot and Distorted versions using this [site](http://boy.co.ua/encode.php) and it worked. Is there another scanner that is able to decode this image?

**Comment by Anollya** [comment]
Hello timwindsor,

when i try "QR Droid", it works fine.
The result is "http://themediaguru.blogspot.com".
QR Droid use ZXing library too.

At work we have a lot of lasered dotted DMC´s. 

Can you fix this issue?
Sorry for my bad english.

**Comment by umcsdon** [comment]
Tried it using zxing barcode scanner on LG G3 (Android 4.4.2). Not working!

**Comment by Anollya** [comment]
Same here.
Can you try QR Droid for testing? Now it shoud be work with your LG G3.
https://play.google.com/store/apps/details?id=la.droid.qr

Here my tests:

Nexus 5
zxing barcode scanner- > not working
QR Droid -> OK

Blackberry Z30
zxing barcode scanner- > not working
WebWorks BB10-Cordova/BarcodeScanner -> not working
QR Droid -> OK

**Comment by umcsdon** [comment]
Yes...QR Droid is working.

**Comment by timwindsor** [comment]
The challenge here is that ZXing used to have a C++ port, which we used in our device, though our [fork](https://github.com/blackberry/zxing) is old. More recently, ZXing dropped most of their ports and is focused only on Java. So we can work on updating our fork, and building in the newest code in the plugin as an included library, but we may not get the latest features that are available in Java. That will require following and porting changes (and going back to pick up what's been missed already). It's not impossible, but certainly is not a quick task. It will take us a while to get there and regular effort to keep up.

**Comment by Anollya** [comment]
Hi timwindsor,

thank's for the information.
I hope it will be fixed as soon as possible, then the barcode scanner is future-proof.

**Comment by umcsdon** [comment]
@timwindsor 

1) We can use java native interface to make function calls
2) We could experiment [ZBar](http://zbar.sourceforge.net/)

**Comment by timwindsor** [comment]
Added integration of a new version of ZXing to the list here #386

**Comment by mig82** [comment]
I've found that adding a blur to a dotted data matrix makes it readable using ZXing. Please have a look at my question in StackOverflow here (and help me find an answer if you can):

https://stackoverflow.com/questions/48908115/scan-a-dotted-laser-dot-peen-data-matrix-with-zxing
