### ISSUE TITLE
LowLatencyAudio, no errors, success callback called, no sound

### ISSUE THREAD

**Issue by khertan** [blackberry/WebWorks-Community-APIs#399]
Hi,

I'm currently trying to use com.blackberry.community.lowlatencyaudio. But while ressource are well preloaded and call to play call sucess callback, but i didn't hear any sound.

> File: <one.wav> is loaded 
> Playing one.wav

I'm using the last 10.3.1 official release for bb10 z10.

Also where is the source of libpgaudio ?
Thanks

**Comment by umcsdon** [comment]
Hi @khertan 

The native implementation can be found [here](https://github.com/blackberry/WebWorks-Community-APIs/tree/master/BB10-Cordova/LowLatencyAudio/plugin/src/blackberry10/native/src).

I will try the sample project now.

**Comment by khertan** [comment]
Thanks, so probably somethings on my side ... i ll try the sample and study what happen on my side.
Will be back soon
