### ISSUE TITLE
how to read sms from central sms database in blackberry10 

### ISSUE THREAD

**Issue by DILEEP-YADAV** [blackberry/WebWorks-Community-APIs#417]
@rtholmes 
@jcmurray 
@daniel-dressler 
@tneil 
@pelegri 

 Hi all ! How can we make central database sms reader plugin for BlackBerry10 Cordova plugin. 
any body can help me.

**Comment by umcsdon** [comment]
Hi @DILEEP-YADAV 

I can work on this one over the weekend.

**Comment by DILEEP-YADAV** [comment]
Hi @umcsdon  Thanks for consider on that, I am  waiting for the same. 
I think native work for the same here https://github.com/blackberry/Cascades-Samples/tree/master/messages/src

I am android developer, I have no idea about blackberry api. But I need please help me.

**Comment by umcsdon** [comment]
Hi @DILEEP-YADAV 

No problem. I will take a look at the native one.

**Comment by umcsdon** [comment]
Hi @DILEEP-YADAV 

Take a look at MessageRetrieve plugin (accountID & messageID required)
https://github.com/blackberry/WebWorks-Community-APIs/tree/master/BB10-Cordova/MessageRetrieve

![image](https://cloud.githubusercontent.com/assets/6402391/9158691/becf92ce-3ee0-11e5-82a9-605442a2683b.png)

**Comment by DILEEP-YADAV** [comment]
But it will retrieve sms or email massage .

**Comment by DILEEP-YADAV** [comment]
@umcsdon 

But I want to retrieve massage using mobile no.  or full text search. How is it possible.

**Comment by DILEEP-YADAV** [comment]
@umcsdon   you have plugin implement  index.html page please share code.

**Comment by umcsdon** [comment]
@DILEEP-YADAV 

No support to retrieve massage using mobile no. or date yet.

**Comment by DILEEP-YADAV** [comment]
@umcsdon  ok  thanks
