### ISSUE TITLE
How to make cordova plugin for sms/mms reader on behalf of sender phone no. or date wise. 

### ISSUE THREAD

**Issue by DILEEP-YADAV** [blackberry/WebWorks-Community-APIs#418]
HI !  @timwindsor 
I am java developer, i know android native api but no idea about blackberry Native api. Please help us.
How to make cordova plugin for sms/mms reader on behalf of sender phone no. or date wise.  ?

**Comment by timwindsor** [comment]
I would suggest starting from the [MessageRetrieve plugin](https://github.com/blackberry/WebWorks-Community-APIs/tree/master/BB10-Cordova/MessageRetrieve) as a basic example, and looking to extend it for SMS messages. Details on the Message Service API, which I think you will need, are here: http://developer.blackberry.com/native/reference/cascades/bb__pim__message__messageservice.html

All the native documentation is available online: http://developer.blackberry.com/native/reference/
